name: Run Selenium Tests with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [master ]

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adoptopenjdk'  # You can also use 'zulu', depending on your preference

    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Install dependencies and run tests
      run: mvn clean install -DsuiteXmlFile=testng.xml

    - name: Upload test reports
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: Reports/SummaryReport.html
