name: Run Selenium Tests with Maven and send an email

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        java-package: 'jdk'
        architecture: 'x64'
        check-latest: false

    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Install dependencies and run tests
      run: mvn clean install -DsuiteXmlFile=testng.xml

    - name: Upload test reports
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: Reports/SummaryReport.html

    - name: Send Summary Report via Email
      run: |
        sudo apt-get install -y mutt  # Install mutt for email sending
        echo "Selenium Test Report attached." | mutt -s "Selenium Test Summary Report" -a Reports/SummaryReport.html -- ${{ secrets.RECIPIENT_EMAIL }}
      env:
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}

